### ISSUE TITLE
Morphic gene list

### ISSUE THREAD

**Issue by damiansm** [whri-phenogenomics/whri-phenogenomics#3]

**Comment by pilarcacheiro** [comment]
- Improve pipeline for gene annotation and share
- Add Pharos / DrugCentral annotations as suggested by Ajay

**Comment by pilarcacheiro** [comment]
This can be merged into https://github.com/whri-phenogenomics/whri-phenogenomics/issues/72

We can close this issue

**Comment by pilarcacheiro** [comment]
To be continued here: https://github.com/whri-phenogenomics/whri-phenogenomics/issues/72
